<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Opérations-sur-les-matrices" data-toc-modified-id="Opérations-sur-les-matrices-1">Opérations sur les matrices</a></span><ul class="toc-item"><li><span><a href="#apply" data-toc-modified-id="apply-1.1">apply</a></span></li><li><span><a href="#lapply" data-toc-modified-id="lapply-1.2">lapply</a></span></li><li><span><a href="#sapply" data-toc-modified-id="sapply-1.3">sapply</a></span></li><li><span><a href="#autre" data-toc-modified-id="autre-1.4">autre</a></span></li></ul></li></ul></div>

In [2]:
options(repr.matrix.max.cols=8, repr.matrix.max.rows=5)

# Opérations sur les matrices


## apply


Nous avons vu qu'il était possible de faire des opérations sur les matrices en ligne ou en colonne. Toutefois, ce n'est pas toutes les fonctions statistiques qui sont applicables sur des colonnes et/ou lignes comme  `colMeans`. Pour appliquer d'utres sortes de fonctions, nous devons utiliser la fonction `apply`.

On peut alors utiliser `apply` lorsqu'on veut appliquer un calcule ou une fonction quelconque (FUN) sur des colonnes ou des lignes d'une matrice (incluant les matrices plus que 2D)

Soit une matrice de 12 premiers entiers;

In [2]:
m<-matrix(1:12, nrow=3)
m

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

Calculons le logarithme naturel de chaque élément de cette matrice:

In [3]:
h<-apply(m, c(1,2), log) #c(1,2) ça veut dire sur ligne et colonne
h

[,1]      [,2]     [,3]     [,4]    
[1,] 0.0000000 1.386294 1.945910 2.302585
[2,] 0.6931472 1.609438 2.079442 2.397895
[3,] 1.0986123 1.791759 2.197225 2.484907

Créons une matrice `3 x 1` qui nous retourne le résultat de la somme de chaque ligne;

In [4]:
h<-matrix(apply(m, 1, sum))
h

[,1]
[1,] 22  
[2,] 26  
[3,] 30

Si nous comparerons à la fonction `rowSums` que nous avons vue;

In [7]:
rowSums(m)

[1] 22 26 30

## lapply

La fonction lapply applique une fonction quelconque (FUN) à tous les éléments d’un vecteur ou d’une liste X et retourne le résultat sous forme de liste.

Dans l'exemple suivant, nous avons une liste de trois vecteurs {vecteur_1, vecteur_2, vecteur_3} de taille différente, on voudrait savoir quelle est la taille de chaque élément, on voudrait la réponse dans une **liste**;

In [4]:
x <- list(vecteur_1 = 1, vecteur_2 = 1:17, vecteur_3 = 55:97) 
lapply(x, FUN = length) 

$vecteur_1
[1] 1

$vecteur_2
[1] 17

$vecteur_3
[1] 43

Dans le résultat ci-haut, la fonction `lapply` nous a retourné une liste de trois éléments avec la taille de chaque vecteur.

Regardons un autre exemple où nous cherchons à créer quatre échantillons aléatoires de taille {5, 6, 7, 8} tirés du vecteur `x= 1 2 3 4 5 6 7 8 9 10`

In [5]:
set.seed(123)
lapply(5:8, sample, x = 1:10)

[[1]]
[1] 3 8 4 7 6

[[2]]
[1] 1 5 8 4 3 9

[[3]]
[1]  5  7 10  1  6  2  9

[[4]]
[1]  4  9  8  5 10  7  3  6

## sapply

Dans certains cas, on voudrait appliquer une fonction quelconque sur une liste, mais on ne veut pas que `R` nous retourne une une liste, on désire plutôt que `R` nous retourne un vecteur. La fonction `sapply` fait exactement cela. Le résultat est donc **s**implifiée par rapport à celui de `lapply`, d’où le nom de la fonction. 

La taille de chaque élément de notre liste;

In [7]:
sapply(x, FUN = length)

vecteur_1 vecteur_2 vecteur_3 
        1        17        43

ou la somme de chaque élément de notre liste `x`

In [6]:
sapply(x, FUN = sum)   

vecteur_1 vecteur_2 vecteur_3 
        1       153      3268

Si le résultat de chaque application de la fonction est un vecteur et que les vecteurs sont tous de la même longueur, alors sapply retourne une matrice, remplie comme toujours par colonne :

In [7]:
(x <- lapply(rep(5, 3), sample, x = 1:10))

[[1]]
[1]  6 10  3  2  9

[[2]]
[1] 10  7  9  1  3

[[3]]
[1] 8 2 3 9 1

In [8]:
sapply(x, sort)

[,1] [,2] [,3]
[1,]  2    1   1   
[2,]  3    3   2   
[3,]  6    7   3   
[4,]  9    9   8   
[5,] 10   10   9

## autre
Il existe d'autres façons de manipuler les matrices, listes, vecteurs ...etc. Dans ce cours nous avons couvert les trois principaux, toutefois, on peut avoir besoin dans certains cas d'utiliser `vapply`, `mapply`, `Map`, `rapply` ou même `tapply` qui s'apparentent tous aux trois fonctions que nous avons couverts avec plus d'options ou format différent du résultat obtenu.